services:
  - type: web
    name: notification-sender
    env: node
    plan: free
    rootDir: .
    buildCommand: yarn install
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false
